# Generated by Django 5.2.5 on 2025-08-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея изображений'},
        ),
    ]
